export default {
  pages: [
    'pages/index/index',
    'pages/button/index',
    'pages/flex/index',
    'pages/typography/index',
    'pages/overlay/index',
    'pages/dialog/index',
    'pages/field/index',
    'pages/cell/index',
    'pages/form/index',
    'pages/radio/index',
    'pages/timeline/index',
    'pages/uploader/index',
    'pages/icon/index',
    'pages/loading/index',
    'pages/stepper/index',
    'pages/card/index',
    'pages/empty/index',
    'pages/tabs/index',
    'pages/popup/index',
    'pages/dragList/index',
    'pages/tooltip/index',
    'pages/spin/index',
    'pages/switch/index',
    'pages/cascader/index',
    'pages/rate/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
};
